#!/usr/bin/env php
<?php declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

$path = $argv[1] ?? 'app';

$bootstrap = new App\Bootstrap;
$container = $bootstrap->bootConsoleApplication();
$presenter = $container->getByType(Nette\Application\IPresenterFactory::class)
	->createPresenter('Home');
$latte = $container->getByType(Nette\Bridges\ApplicationLatte\TemplateFactory::class)
	->createTemplate($presenter)
	->getLatte();

$latte->addExtension(new Latte\Tools\LinterExtension);

$linter = new Latte\Tools\Linter($latte, strict: true);
$ok = $linter->scanDirectory($path);
exit($ok ? 0 : 1);